<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AcademiaDigital.Finance.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.4.13" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcademiaDigital.Finance.Application\AcademiaDigital.Finance.Application.csproj" />
    <ProjectReference Include="..\AcademiaDigital.Finance.Infrastructure\AcademiaDigital.Finance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\AcademiaDigital.Finance.Contracts\AcademiaDigital.Finance.Contracts.csproj" />
  </ItemGroup>

</Project>
