// <auto-generated />
using System;
using AcademiaDigital.Finance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcademiaDigital.Finance.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.BillingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year");

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CareerId", "AcademicYear", "Name")
                        .IsUnique();

                    b.ToTable("BillingPlans", "finance");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.BillingPlanItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BillingPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_plan_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("FinancialConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_concept_id");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("installment_number");

                    b.HasKey("Id");

                    b.HasIndex("FinancialConceptId");

                    b.HasIndex("BillingPlanId", "DueDate");

                    b.HasIndex("BillingPlanId", "FinancialConceptId", "InstallmentNumber")
                        .IsUnique();

                    b.ToTable("BillingPlanItems", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_BillingPlanItems_Installment", "installment_number > 0");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.DebtGenerationBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BillingPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_plan_id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<long>("GeneratedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("generated_by_user_id");

                    b.Property<int>("GeneratedDebtCount")
                        .HasColumnType("integer")
                        .HasColumnName("generated_debt_count");

                    b.Property<decimal>("GeneratedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("generated_total");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("BillingPlanId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("DebtGenerationBatches", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_DebtGenerationBatches_Count", "generated_debt_count >= 0");

                            t.HasCheckConstraint("CK_DebtGenerationBatches_Total", "generated_total >= 0");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.FinancialBenefit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentage");

                    b.Property<int?>("ScholarshipId")
                        .HasColumnType("integer")
                        .HasColumnName("scholarship_id");

                    b.Property<int?>("StudentCondition")
                        .HasColumnType("integer")
                        .HasColumnName("student_condition");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CareerId", "IsActive");

                    b.ToTable("FinancialBenefits", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_FinancialBenefits_Percentage", "percentage > 0 AND percentage <= 100");

                            t.HasCheckConstraint("CK_FinancialBenefits_Scholarship", "(kind = 0 AND scholarship_id IS NULL) OR (kind = 1 AND scholarship_id IS NOT NULL)");

                            t.HasCheckConstraint("CK_FinancialBenefits_Validity", "valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.FinancialConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FinancialConcepts", "finance");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.FinancialRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("CareerId")
                        .HasColumnType("integer")
                        .HasColumnName("career_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FinancialConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_concept_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("StudentCondition")
                        .HasColumnType("integer")
                        .HasColumnName("student_condition");

                    b.Property<decimal>("SurchargePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("surcharge_percentage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CareerId", "AcademicYear");

                    b.HasIndex("FinancialConceptId", "CareerId", "AcademicYear")
                        .IsUnique()
                        .HasDatabaseName("UX_FinancialRates_Default")
                        .HasFilter("student_condition IS NULL");

                    b.HasIndex("FinancialConceptId", "CareerId", "AcademicYear", "StudentCondition")
                        .IsUnique()
                        .HasFilter("student_condition IS NOT NULL");

                    b.ToTable("FinancialRates", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_FinancialRates_Amount", "amount > 0");

                            t.HasCheckConstraint("CK_FinancialRates_Surcharge", "surcharge_percentage >= 0 AND surcharge_percentage <= 100");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ConfirmationIdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmation_idempotency_key");

                    b.Property<DateTime?>("ConfirmationRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmation_requested_at");

                    b.Property<long?>("ConfirmationRequestedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmation_requested_by_user_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<long?>("ConfirmedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_reference");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StudentDni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_dni");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("student_name");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationIdempotencyKey")
                        .IsUnique()
                        .HasFilter("confirmation_idempotency_key IS NOT NULL");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("StudentId", "CreatedAt");

                    b.ToTable("Payments", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "amount > 0");

                            t.HasCheckConstraint("CK_Payments_Currency", "currency = 'ARS'");

                            t.HasCheckConstraint("CK_Payments_Status", "status >= 0 AND status <= 4");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<long>("StudentDebtId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_debt_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentDebtId");

                    b.HasIndex("PaymentId", "StudentDebtId")
                        .IsUnique();

                    b.ToTable("PaymentAllocations", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentAllocations_Amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.ToTable("PaymentMethods", "finance");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CASH",
                            DisplayOrder = 1,
                            IsActive = true,
                            Kind = 0,
                            Name = "Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BANK_TRANSFER",
                            DisplayOrder = 2,
                            IsActive = true,
                            Kind = 1,
                            Name = "Transferencia bancaria"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DEBIT_CARD",
                            DisplayOrder = 3,
                            IsActive = true,
                            Kind = 2,
                            Name = "Tarjeta de débito"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CREDIT_CARD",
                            DisplayOrder = 4,
                            IsActive = true,
                            Kind = 3,
                            Name = "Tarjeta de crédito"
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentReconciliation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("PaymentReconciliations", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentReconciliations_Decision", "decision IN (0, 1)");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentReversal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PaymentReversals", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentReversals_Amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_name");

                    b.Property<string>("FiscalCae")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fiscal_cae");

                    b.Property<string>("FiscalQrData")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("fiscal_qr_data");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<long>("IssuedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by_user_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("receipt_number");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("SequenceNumber")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Receipts", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_Receipts_Sequence", "sequence_number > 0");

                            t.HasCheckConstraint("CK_Receipts_Status", "status >= 0 AND status <= 2");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.ReceiptSequence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("Id");

                    b.ToTable("ReceiptSequences", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_ReceiptSequences_Singleton", "id = 1 AND last_value >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastValue = 0L
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.StudentDebt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppliedBenefitId")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_benefit_id");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_amount");

                    b.Property<long>("BillingPlanItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("billing_plan_item_id");

                    b.Property<string>("CalculationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calculation_snapshot_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<long>("DebtGenerationBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("debt_generation_batch_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("FinancialConceptId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_concept_id");

                    b.Property<long>("FinancialRateId")
                        .HasColumnType("bigint")
                        .HasColumnName("financial_rate_id");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("StudentCareerId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_career_id");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<decimal>("SurchargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("surcharge_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.HasIndex("AppliedBenefitId");

                    b.HasIndex("BillingPlanItemId");

                    b.HasIndex("FinancialConceptId");

                    b.HasIndex("FinancialRateId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StudentCareerId", "BillingPlanItemId")
                        .IsUnique();

                    b.HasIndex("DebtGenerationBatchId", "StudentCareerId", "BillingPlanItemId")
                        .IsUnique();

                    b.HasIndex("StudentId", "Status", "DueDate");

                    b.ToTable("StudentDebts", "finance", t =>
                        {
                            t.HasCheckConstraint("CK_StudentDebts_Amounts", "base_amount > 0 AND surcharge_amount >= 0 AND discount_amount >= 0 AND total_amount >= 0 AND paid_amount >= 0 AND paid_amount <= total_amount");

                            t.HasCheckConstraint("CK_StudentDebts_Currency", "currency = 'ARS'");
                        });
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.BillingPlanItem", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.BillingPlan", "BillingPlan")
                        .WithMany("Items")
                        .HasForeignKey("BillingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.FinancialConcept", "FinancialConcept")
                        .WithMany()
                        .HasForeignKey("FinancialConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingPlan");

                    b.Navigation("FinancialConcept");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.DebtGenerationBatch", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.BillingPlan", "BillingPlan")
                        .WithMany()
                        .HasForeignKey("BillingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillingPlan");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.FinancialRate", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.FinancialConcept", "FinancialConcept")
                        .WithMany()
                        .HasForeignKey("FinancialConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinancialConcept");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.Payment", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.StudentDebt", "StudentDebt")
                        .WithMany()
                        .HasForeignKey("StudentDebtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("StudentDebt");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentReconciliation", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.Payment", "Payment")
                        .WithMany("Reconciliations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.PaymentReversal", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.Payment", "Payment")
                        .WithMany("Reversals")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.Payment", "Payment")
                        .WithOne("Receipt")
                        .HasForeignKey("AcademiaDigital.Finance.Domain.Entities.Receipt", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.StudentDebt", b =>
                {
                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.FinancialBenefit", "AppliedBenefit")
                        .WithMany()
                        .HasForeignKey("AppliedBenefitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.BillingPlanItem", "BillingPlanItem")
                        .WithMany()
                        .HasForeignKey("BillingPlanItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.DebtGenerationBatch", "DebtGenerationBatch")
                        .WithMany("Debts")
                        .HasForeignKey("DebtGenerationBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.FinancialConcept", "FinancialConcept")
                        .WithMany()
                        .HasForeignKey("FinancialConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcademiaDigital.Finance.Domain.Entities.FinancialRate", "FinancialRate")
                        .WithMany()
                        .HasForeignKey("FinancialRateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppliedBenefit");

                    b.Navigation("BillingPlanItem");

                    b.Navigation("DebtGenerationBatch");

                    b.Navigation("FinancialConcept");

                    b.Navigation("FinancialRate");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.BillingPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.DebtGenerationBatch", b =>
                {
                    b.Navigation("Debts");
                });

            modelBuilder.Entity("AcademiaDigital.Finance.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Receipt");

                    b.Navigation("Reconciliations");

                    b.Navigation("Reversals");
                });
#pragma warning restore 612, 618
        }
    }
}
