networks:
  app_network:
    driver: bridge

services:

  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD:-Admin1234!}"
      MSSQL_PID: Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd",
             "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD:-Admin1234!}",
             "-Q", "SELECT 1", "-No"]
      interval: 15s
      retries: 6
      start_period: 30s
    networks:
      - app_network

  backend:
    container_name: dotnet_backend
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - backend_files:/app/data/files
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=AcademiaDigital;User Id=sa;Password=${SA_PASSWORD:-Admin1234!};TrustServerCertificate=True;
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - Jwt__ExpirationDays=7
      - AdmissionStorage__RootPath=/app/data/files
      - Cors__AllowedOrigins__0=http://localhost:3000
      - Cors__AllowedOrigins__1=http://localhost:4200
      - Cors__AllowedOrigins__2=https://itsc-app.dryvn.org

volumes:
  sqlserver_data:
  backend_files:
